# Generated by Django 4.0.3 on 2022-04-07 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='followed', through='review.UserFollows', to=settings.AUTH_USER_MODEL),
        ),
    ]
